### ISSUE TITLE
Parameter that is both required and read-only

### ISSUE THREAD

**Issue by lanzz** [mission-liao/pyswagger#81]
Let's say I have a spec that has a `POST /entity` endpoint, whose body is `#/definitions/Entity`. `Entity` is a schema that's an object with an `id` key, which is both required and read-only; my intention is that this key is required in responses, but _forbidden_ in requests. This does not seem supported by `pyswagger` — as long as I have the key in the `required` list, it will not validate a _request_ that does not have it, even though `readOnly: true` forbids it in a request.

```yaml
...
definitions:
  entity:
    type: object
      required:
        id
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
...
```

Rationale: It is not possible to provide an id when _creating_ an entity, and when updating an entity its id will be provided in the URL and it makes no sense to allow changing the id (i.e. provide one id in the URL and a different id in the body), so there is no legitimate situation where that id will make sense in a request, but it is required to be present in a response body so that unit tests using the API spec will fail if they don't see it there.
